In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
#carrega base de dados de imagens de roupas
fashion_mnist = keras.datasets.fashion_mnist
#separa dado em treino e teste
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [3]:
#tamanho da base de dados
    #elementos de treino com a matriz M x N a forma de apresentação
train_images.shape

(60000, 28, 28)

In [4]:
#tamanho do conjunto dos rótulos de treino
len(train_labels)

60000

In [5]:
#quantidade de labels distintas na base de treino
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
#cada pixel vai de zero a 255
    #convertendo para uma escala entre 0 e 1 (semelhante ao uso de MinMaxScaler)
#prepara o conjunto de dados para uso na rede neural

train_images = train_images / 255.0

test_images = test_images / 255.0

In [10]:
#definição do modelo neural
    #keras.layers.Flatten -> camadas sequenciais, ou seja, assim que termina a execução de uma camada já executa a próxima
        # -> traduz a matriz de 28 por 28 para um vetor
        #input_shape -> tamanho da matriz
    #keras.layers.Dense -> (128, activation=tf.nn.relu) -> camadas comuns de rede neural (transição entre as camadas)
        # função de ativação ReLu (negativo é zero, positivo mantém)
    #keras.layers.Dense -> (10)
        # softmax -> função para classificação (camada de saída com 10 neurônios)
            #esta ultima camada deve ter a mesma quantidade de labels distintas de classificação
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

#quantos pesos e estrutura na rede neural
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
#compila o modelo
    #optimizer = 'adam' -> otimizador para construção de pesos
    #loss='sparse_categorical_crossentropy' -> métricas de erros 
        #sparse_categorical_crossentropy -> trabalha com resultados próximos a zero
    #metrics=['accuracy'] -> porcentagem de elementos corretos
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
#treina o modelo
    #epochs=5 -> 5 iterações (épocas) de treinamento
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6290 - accuracy: 0.7835
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3898 - accuracy: 0.8613
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3486 - accuracy: 0.8723
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3112 - accuracy: 0.8846
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2931 - accuracy: 0.8903


In [13]:
#avaliação com dados de teste
    #test_loss -> erros
    #test_acc -> acertos
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 693us/step - loss: 0.3405 - accuracy: 0.8783
Test accuracy: 0.8783000111579895


In [14]:
#avaliar individualmente os dados
    #cria uma predição para cada imagem de teste
predictions = model.predict(test_images)

In [15]:
predictions[0]

array([1.1883544e-06, 3.2256125e-06, 5.0867692e-07, 5.4191237e-06,
       6.4571526e-07, 1.0329544e-02, 1.8423578e-06, 6.3110664e-02,
       3.0019786e-05, 9.2651689e-01], dtype=float32)

In [16]:
#a classificação é dada pelo maior valor do predict
#np.argmax -> pega o maior valor do predict para usar como classe
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
#classificação de apenas uma imagem
img = test_images[0]

print(img.shape)

(28, 28)


In [19]:
#np.expand_dims -> o modelo espera um vetor de imagem. O expand.dims tranforma a matriz em vetor
    #(img,0) -> img é o valor a ser convertido para vetor.
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [20]:
#predição de uma única imagem
predictions_single = model.predict(img)

print(predictions_single)

[[1.1883568e-06 3.2256157e-06 5.0867646e-07 5.4191287e-06 6.4571526e-07
  1.0329548e-02 1.8423596e-06 6.3110664e-02 3.0019786e-05 9.2651689e-01]]


In [21]:
#imprime classe na qual foi classificada a imagem
np.argmax(predictions_single[0])

9